# This is a config for E2B sandbox template.
# You can use template ID (l9dpsr9jnhk86hqbtozt) or template name (rushed-nextjs-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("rushed-nextjs-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("rushed-nextjs-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('rushed-nextjs-template')

team_id = "4f145bbd-574d-49c8-b091-3241ea2a6bd4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "mspace-nextjs-template"
template_id = "nc5y6eeoc52c2qun1dor"
